name: Build and deploy Python app to Azure Web App - msdocs-python-webapp-quickstart-HSS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest   # Use Windows runner since you're using Windows 11

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Updated Python version

      - name: Create and start virtual environment (Windows)
        run: |
          python -m venv .venv  # Ensure the venv is created with the .venv name
          .\.venv\Scripts\activate  # Activate virtual environment on Windows

      - name: Install dependencies
        run: .\.venv\Scripts\pip install -r msdocs-python-flask-webapp-quickstart/requirements.txt
  # Use correct pip path for Windows

      # Optional: Add step to run tests here (PyTest, etc.)

      - name: Zip artifact for deployment (Optional, remove if not needed)
        run: tar -czvf release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: windows-latest  # Ensure this matches your build job runner
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: tar -xvf release.zip   # Windows can handle tar/gzip now in GitHub runners

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2DB96C016EE54063B90DAC1E73DD66F5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0B1190D7F5704F71B6EB46E4825D3509 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E311F0F5AFAD40F3B46B34E4E348D178 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'msdocs-python-webapp-quickstart-HSS'
          slot-name: 'Production'
